title: Trịnh Hùng       # Tiêu đề blog
tagline: Vui Chơi Giải Trí   # Mô tả ngắn
url: 'https://trinhhung1095.github.io' # URL của bạn
twitter:
  username: https://x.com/Trinhhung1095   # Điền Twitter nếu có (để hiện icon)
github:
  username: trinhhung1095.github.io    # Điền GitHub username của bạn
# Và rất nhiều tùy chọn khác trong file này
